// CLEAR
export const CLEAR_STORE = 'CLEAR_STORE';

// ACOUNT
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const GET_USER_INFO = 'GET_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const GET_FRIEND_INFO = 'GET_FRIEND_INFO';

// CHAT
export const SEARCH_CONTACT = 'SEARCH_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const GET_LIST_CONTACT = 'GET_LIST_CONTACT';
export const START_CONVERSATION = 'START_CONVERSATION';
export const LOAD_CONVERSATION = 'LOAD_CONVERSATION';
export const GET_CONVERSATION_DETAIL = 'GET_CONVERSATION_DETAIL';
export const GET_LIST_CONVERSATION = 'GET_LIST_CONVERSATION';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_CHAT_HISTORY = 'GET_CHAT_HISTORY';
export const LOAD_MORE_HISTORY = 'LOAD_MORE_HISTORY';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';

export const GET_LIST_AVAILABLE_CONTACT = 'GET_LIST_AVAILABLE_CONTACT';
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const GET_GROUP_CONVERSATION = 'GET_GROUP_CONVERSATION';
export const CHANGE_GROUP_CONVERSATION_NAME = 'CHANGE_GROUP_CONVERSATION_NAME';
export const CHANGE_GROUP_CONVERSATION_AVATAR = 'CHANGE_GROUP_CONVERSATION_AVATAR';
export const ADD_FRIEND_TO_CONVERSATION = 'ADD_FRIEND_TO_CONVERSATION';

export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const CONNECT_SOCKET_STATUS = 'CONNECT_SOCKET_STATUS';
export const SHOW_CALL_REQUEST = 'SHOW_CALL_REQUEST';
export const START_VIDEO_CALL = 'START_VIDEO_CALL';
export const START_CALL = 'START_CALL';
export const RECEIVE_CALL_SIGNAL = 'RECEIVE_CALL_SIGNAL';